apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-323c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-323c"
  template:
    metadata:
      labels:
        app: "myaks-323c"
    spec:
      containers:
        - name: "myaks-323c"
          image: "myeshopregistry.azurecr.io/myaks"
          ports:
          - containerPort: 80